import { uuidv7 } from "uuidv7";
import { Account, Budget, Category, Payee } from "./types";
import {
  BANK,
  CASH,
  EUR,
  FIXED,
  FLEXIBLE,
  SAVINGS,
  SINK_FUNDS,
  THIS_MONTH_ONLY,
} from "./constants";

const budgetId = uuidv7();

export const SAMPLE_BUDGET: Budget = {
  id: budgetId,
  name: "Family",
  currency: EUR,
  payDay: 21,
};

export const SAMPLE_PAYEES: Payee[] = [
  {
    id: uuidv7(),
    budgetId,
    name: "Shop",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Amazon",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Pharmacy",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Bakery",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Salary",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Parking",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Fruit & Veg",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Petrol Station",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "School",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "School Transport",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Eco Veggies",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Diputación",
  },
];

export const SAMPLE_ACCOUNTS: Account[] = [
  {
    id: uuidv7(),
    budgetId,
    name: "Cash",
    type: CASH,
    balanceCents: 10000,
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Unicaja",
    type: BANK,
    balanceCents: 20000,
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Revolut",
    type: BANK,
    balanceCents: 15000,
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Caja Rural",
    type: BANK,
    balanceCents: 35000,
  },
];

export const SAMPLE_CATEGORIES: Category[] = [
  {
    id: uuidv7(),
    budgetId,
    name: "Trip",
    group: THIS_MONTH_ONLY,
    balanceCents: 10000,
    notes: "",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Wardrobe Painting",
    group: THIS_MONTH_ONLY,
    balanceCents: 5000,
    notes: "",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Once Off",
    group: THIS_MONTH_ONLY,
    balanceCents: 223300,
    notes: "",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Amazon Prime",
    group: SINK_FUNDS,
    balanceCents: 1061,
    notes: "€5.62/month - Goal: €49.90",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Car Service",
    group: SINK_FUNDS,
    balanceCents: 17000,
    notes: "€20/month - Goal: €240",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Car Tax",
    group: SINK_FUNDS,
    balanceCents: 6615,
    notes: "€5.13/month - Goal: €66.15",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Christmas Gifts",
    group: SINK_FUNDS,
    balanceCents: 17500,
    notes: "€15/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Clothes",
    group: SINK_FUNDS,
    balanceCents: 1000,
    notes: "€20/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Wedding Present",
    group: SINK_FUNDS,
    balanceCents: 3000,
    notes: "€30/month - Goal: €200",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Extra Month",
    group: SINK_FUNDS,
    balanceCents: 5000,
    notes: "€50/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Gifts",
    group: SINK_FUNDS,
    balanceCents: 5000,
    notes: "€20/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Greenpeace",
    group: SINK_FUNDS,
    balanceCents: 1200,
    notes: "€12/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Protein",
    group: SINK_FUNDS,
    balanceCents: 1000,
    notes: "€10/month - Goal: €80",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Water Filter",
    group: SINK_FUNDS,
    balanceCents: 1423,
    notes: "€3.89/month - Goal: €57",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Food",
    group: FLEXIBLE,
    balanceCents: 63902,
    notes: "€800/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Bills",
    group: FLEXIBLE,
    balanceCents: 37639,
    notes: "Mortgages, Insurance, Diputación, Electricity",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Fuel",
    group: FLEXIBLE,
    balanceCents: 2000,
    notes: "",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Child Care",
    group: FLEXIBLE,
    balanceCents: 24400,
    notes: "€150/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Bank Commission",
    group: FIXED,
    balanceCents: 2400,
    notes: "€12/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Better Me Kenya",
    group: FIXED,
    balanceCents: 0,
    notes: "€26/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "School",
    group: FIXED,
    balanceCents: 0,
    notes: "€290/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Garage",
    group: FIXED,
    balanceCents: 0,
    notes: "€10/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "School Transport",
    group: FIXED,
    balanceCents: 0,
    notes: "€50/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Family Support",
    group: FIXED,
    balanceCents: 17500,
    notes: "€175/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Pension",
    group: FIXED,
    balanceCents: 5000,
    notes: "€50/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Ready To Invest",
    group: FLEXIBLE,
    balanceCents: 69976,
    notes: "",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Spotify",
    group: FIXED,
    balanceCents: 1099,
    notes: "€10.99/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Guilt-Free Spending",
    group: FIXED,
    balanceCents: 20458,
    notes: "€450/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Child Savings",
    group: SAVINGS,
    balanceCents: 0,
    notes: "€25/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Car Savings",
    group: SAVINGS,
    balanceCents: 0,
    notes: "€20/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Personal Savings",
    group: SAVINGS,
    balanceCents: 0,
    notes: "€50/month",
  },
  {
    id: uuidv7(),
    budgetId,
    name: "Holiday Savings",
    group: SAVINGS,
    balanceCents: 0,
    notes: "€150/month",
  },
];
